# Generated by Django 5.2.7 on 2025-10-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='tipo',
            field=models.CharField(choices=[('salon', 'Salón Principal'), ('gimnasio', 'Gimnasio'), ('parqueo', 'Parqueo'), ('piscina', 'Piscina'), ('terraza', 'Terraza')], max_length=20),
        ),
    ]
