# Generated by Django 5.2.7 on 2025-10-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_add_logout_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('residente', 'Residente'), ('personal', 'Personal'), ('junta', 'Junta'), ('admin', 'Administrador')], default='residente', max_length=20),
        ),
    ]
